/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Pablo
 * Created: 15-12-2017
 */
CREATE TABLE "USUARIO01"."EMPLEADOS" 
   (	"CODIGO" NUMBER(3,0) NOT NULL ENABLE, 
	"RUT" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"APELLIDO" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"CELULAR" NUMBER(9,0) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"SUELDO_BRUTO" NUMBER(7,0) NOT NULL ENABLE, 
	"EST_CIVIL" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"NOM_DEPTO" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "EMPLEADOS_PK" PRIMARY KEY ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USUARIO01"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USUARIO01" ;
